export const mockClassResults = [
  { id: 1, name: "Ananya Sharma", subjects: [{ name: "Mathematics", m: 95 }, { name: "Physics", m: 88 }, { name: "Chemistry", m: 92 }, { name: "Biology", m: 90 }, { name: "History", m: 85 }, { name: "Geography", m: 88 }, { name: "Political Science", m: 92 }, { name: "Economics", m: 89 }, { name: "English", m: 91 }, { name: "Language", m: 95 }, { name: "Computer Science", m: 98 }] },
  { id: 2, name: "Rohan Patel", subjects: [{ name: "Mathematics", m: 72 }, { name: "Physics", m: 65 }, { name: "Chemistry", m: 70 }, { name: "Biology", m: 68 }, { name: "History", m: 75 }, { name: "Geography", m: 72 }, { name: "Political Science", m: 70 }, { name: "Economics", m: 65 }, { name: "English", m: 72 }, { name: "Language", m: 70 }, { name: "Computer Science", m: 75 }] },
  { id: 3, name: "Vikram Singh", subjects: [{ name: "Mathematics", m: 30 }, { name: "Physics", m: 35 }, { name: "Chemistry", m: 28 }, { name: "Biology", m: 32 }, { name: "History", m: 40 }, { name: "Geography", m: 35 }, { name: "Political Science", m: 33 }, { name: "Economics", m: 30 }, { name: "English", m: 35 }, { name: "Language", m: 32 }, { name: "Computer Science", m: 40 }] },
  { id: 4, name: "Priya Das", subjects: [{ name: "Mathematics", m: 88 }, { name: "Physics", m: 90 }, { name: "Chemistry", m: 85 }, { name: "Biology", m: 87 }, { name: "History", m: 82 }, { name: "Geography", m: 85 }, { name: "Political Science", m: 88 }, { name: "Economics", m: 90 }, { name: "English", m: 88 }, { name: "Language", m: 85 }, { name: "Computer Science", m: 92 }] },
  { id: 5, name: "Ishaan Gupta", subjects: [{ name: "Mathematics", m: 60 }, { name: "Physics", m: 58 }, { name: "Chemistry", m: 62 }, { name: "Biology", m: 65 }, { name: "History", m: 60 }, { name: "Geography", m: 55 }, { name: "Political Science", m: 62 }, { name: "Economics", m: 58 }, { name: "English", m: 60 }, { name: "Language", m: 62 }, { name: "Computer Science", m: 65 }] },
  { id: 6, name: "Sneha Reddy", subjects: [{ name: "Mathematics", m: 92 }, { name: "Physics", m: 94 }, { name: "Chemistry", m: 90 }, { name: "Biology", m: 95 }, { name: "History", m: 88 }, { name: "Geography", m: 90 }, { name: "Political Science", m: 92 }, { name: "Economics", m: 94 }, { name: "English", m: 90 }, { name: "Language", m: 92 }, { name: "Computer Science", m: 96 }] },
  { id: 7, name: "Arjun Mehta", subjects: [{ name: "Mathematics", m: 40 }, { name: "Physics", m: 42 }, { name: "Chemistry", m: 38 }, { name: "Biology", m: 45 }, { name: "History", m: 50 }, { name: "Geography", m: 42 }, { name: "Political Science", m: 40 }, { name: "Economics", m: 38 }, { name: "English", m: 45 }, { name: "Language", m: 42 }, { name: "Computer Science", m: 48 }] },
  { id: 8, name: "Kavita Rao", subjects: [{ name: "Mathematics", m: 78 }, { name: "Physics", m: 80 }, { name: "Chemistry", m: 75 }, { name: "Biology", m: 82 }, { name: "History", m: 78 }, { name: "Geography", m: 80 }, { name: "Political Science", m: 75 }, { name: "Economics", m: 80 }, { name: "English", m: 78 }, { name: "Language", m: 75 }, { name: "Computer Science", m: 82 }] },
  { id: 9, name: "Rahul Verma", subjects: [{ name: "Mathematics", m: 55 }, { name: "Physics", m: 52 }, { name: "Chemistry", m: 58 }, { name: "Biology", m: 50 }, { name: "History", m: 55 }, { name: "Geography", m: 52 }, { name: "Political Science", m: 55 }, { name: "Economics", m: 52 }, { name: "English", m: 58 }, { name: "Language", m: 55 }, { name: "Computer Science", m: 50 }] },
  { id: 10, name: "Megha Jain", subjects: [{ name: "Mathematics", m: 85 }, { name: "Physics", m: 82 }, { name: "Chemistry", m: 88 }, { name: "Biology", m: 85 }, { name: "History", m: 90 }, { name: "Geography", m: 85 }, { name: "Political Science", m: 82 }, { name: "Economics", m: 88 }, { name: "English", m: 85 }, { name: "Language", m: 82 }, { name: "Computer Science", m: 88 }] }
];