import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

const BRAND = {
  accent: [46, 79, 163],     // #2e4fa3 — matches reportShared.jsx ACCENT
  heading: [26, 31, 54],     // #1a1f36
  subtext: [122, 127, 142],  // #7a7f8e
  muted: [159, 165, 184],    // #9fa5b8
  stripe: [247, 248, 252],   // #f7f8fc
};


export function exportReportToPDF({
  title,
  schoolName = "School ERP",
  generatedBy = "Admin",
  summary = [],
  columns,
  rows,
  fileName,
  orientation,
}) {
  const finalOrientation = orientation || (columns.length > 6 ? "landscape" : "portrait");
  const doc = new jsPDF({ orientation: finalOrientation, unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 40;

  const now = new Date();
  const dateStr = now.toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" });
  const timeStr = now.toLocaleTimeString("en-IN", { hour: "2-digit", minute: "2-digit" });

  // ── Header ──────────────────────────────────────────────────────────────
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.setTextColor(...BRAND.heading);
  doc.text(schoolName, margin, 40);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.setTextColor(...BRAND.accent);
  doc.text(title, margin, 58);

  doc.setFontSize(9);
  doc.setTextColor(...BRAND.muted);
  doc.text(`Generated on: ${dateStr}  •  ${timeStr}`, pageWidth - margin, 38, { align: "right" });
  doc.text(`Generated by: ${generatedBy}`, pageWidth - margin, 52, { align: "right" });

  doc.setDrawColor(232, 234, 240);
  doc.setLineWidth(1);
  doc.line(margin, 68, pageWidth - margin, 68);

  let cursorY = 86;

  // ── Summary statistics ──────────────────────────────────────────────────
  if (summary.length > 0) {
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...BRAND.accent);
    const line = summary.map((s) => `${s.label}: ${s.value}`).join("      ");
    doc.text(line, margin, cursorY);
    cursorY += 18;
  }

  // ── Table ───────────────────────────────────────────────────────────────
  autoTable(doc, {
    head: [columns],
    body: rows,
    startY: cursorY,
    margin: { left: margin, right: margin, bottom: 44 },
    styles: {
      fontSize: 8,
      cellPadding: 5,
      textColor: BRAND.heading,
      lineColor: [232, 234, 240],
      lineWidth: 0.5,
      overflow: "linebreak",
    },
    headStyles: {
      fillColor: BRAND.accent,
      textColor: 255,
      fontStyle: "bold",
      fontSize: 8.5,
    },
    alternateRowStyles: { fillColor: BRAND.stripe },
    theme: "striped",
    tableWidth: "auto",
    rowPageBreak: "avoid",
  });

  // ── Footer (page numbers) — applied to every page after layout is final ──
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(...BRAND.muted);
    doc.text(`${schoolName} · Reports Module · Confidential`, margin, pageHeight - 20);
    doc.text(`Page ${i} of ${pageCount}`, pageWidth - margin, pageHeight - 20, { align: "right" });
  }

  const safeName = (fileName || title || "Report").replace(/[^\w-]+/g, "_");
  const dateForFile = now.toISOString().slice(0, 10);
  doc.save(`${safeName}_${dateForFile}.pdf`);
}